config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Root path
  root "pokemons#index"

  # About path
  get "about", to: "pages#about"

  # Pokemons path
  get "pokemons", to: "pokemons#index"
  get "pokemons/search", to: "pokemons#search"
  get "pokemons/:id", to: "pokemons#show", as: :pokemon

  # Types path
  get "types", to: "types#index"
  get "types/:id", to: "types#show", as: :type

  # Trainers path
  get "trainers", to: "trainers#index"
  get "trainers/:id", to: "trainers#show", as: :trainer

  # Abilities path
  get "abilities", to: "abilities#index"
  get "abilities/:id", to: "abilities#show", as: :ability

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/ability.rb
class Ability < ApplicationRecord
  has_many :pokemon_abilities, dependent: :destroy
  has_many :pokemons, through: :pokemon_abilities

  validates :name, presence: true, uniqueness: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  has_many :pokemon_types, dependent: :destroy
  has_many :types, through: :pokemon_types

  has_many :pokemon_abilities, dependent: :destroy
  has_many :abilities, through: :pokemon_abilities

  has_many :pokemon_trainers, dependent: :destroy
  has_many :trainers, through: :pokemon_trainers

  validates :name, presence: true, uniqueness: true
  validates :height, :weight, numericality: { greater_than: 0 }, allow_nil: true
end

app/models/pokemon_ability.rb
class PokemonAbility < ApplicationRecord
  belongs_to :pokemon
  belongs_to :ability

  validates :pokemon_id, uniqueness: { scope: :ability_id}
end

app/models/pokemon_trainer.rb
class PokemonTrainer < ApplicationRecord
  belongs_to :pokemon
  belongs_to :trainer
end

app/models/pokemon_type.rb
class PokemonType < ApplicationRecord
  belongs_to :pokemon
  belongs_to :type

  validates :pokemon_id, uniqueness: { scope: :type_id}
end

app/models/trainer.rb
class Trainer < ApplicationRecord
  has_many :pokemon_trainers, dependent: :destroy
  has_many :pokemons, through: :pokemon_trainers

  validates :name, presence: true
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :pokemon_types, dependent: :destroy
  has_many :pokemons, through: :pokemon_types

  validates :name, presence: true, uniqueness: true
end

app/controllers/abilities_controller.rb
class AbilitiesController < ApplicationController
  def index
    @abilities = Ability.all
  end

  def show
    @ability = Ability.find(params[:id])
    @pokemons = @ability.pokemons
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  def index
    @pokemons = Pokemon.order(:name).page(params[:page]).per(20)
  end

  def search
    query = params[:query].to_s.downcase
    @pokemons= Pokemon.where("LOWER(name) LIKE ?", "%#{query}%").limit(10)

    render json: @pokemons.map { |p|
      {
        id: p.id,
        name: p.name,
        sprite_url: p.sprite_url
      }
    }
  end

  def show
    @pokemon = Pokemon.find(params[:id])
    @types = @pokemon.types
    @abilities = @pokemon.abilities
    @trainers = @pokemon.trainers
  end
end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
  def index
    @trainers = Trainer.all
  end

  def show
    @trainer = Trainer.find(params[:id])
    @pokemons = @trainer.pokemons
  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  def index
    @types = Type.all
  end

  def show
    @type = Type.find(params[:id])
    @pokemons = @type.pokemons
  end
end

app/helpers/abilities_helper.rb
module AbilitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/abilities/index.html.erb
<h1>Abilities#index</h1>
<p>Find me in app/views/abilities/index.html.erb</p>

app/views/abilities/show.html.erb
<h1>Abilities#show</h1>
<p>Find me in app/views/abilities/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title><%= content_for(:title) || "Agile Fswd Intro To Rails" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <link rel="stylesheet" href="https://unpkg.com/leaflet/dist/leaflet.css" />
    <script src="https://unpkg.com/leaflet/dist/leaflet.js"></script>

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.4/css/bulma.min.css">
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
</head>

<body>
    <nav class="navbar is-transparent center pokemon-navbar">
        <%= link_to "All pokemons", root_path, class:"button is-info is-inverted #{("is-active") if controller_name == "pokemons"}" %>
        <%= link_to "Trainers", trainers_path, class:"button is-info is-inverted #{("is-active") if controller_name == "trainers"}"%>
        <%= link_to "Types", types_path, class:"button is-info is-inverted #{("is-active") if controller_name == "types"}" %>
        <%= link_to "About", about_path, class:"button is-info is-inverted #{("is-active") if controller_name == "about"}" %>
    </nav>
    <div class="body-div center">
        <%= yield %>
    </div>
</body>

</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pokemons/index.html.erb
<div class="pokemon-container container">
    <div class="is-size-5 has-text-centered pokemon-header">
        <h1>
            All pokemons
        </h1>
    </div>

    <div class="center has-text-centered search-div">
        <input class="input is-info is-inverted search-input" id="pokemon-search" placeholder="Search for a pokemon" />
        <div id="search-results" class="dropdown-menu container center has-text-centered">
            <div class="dropdown-content">
            </div>
        </div>
    </div>
    <table class="all-pokemon container center table ">
        <thead class="pokemon-head">
            <tr class="pokemon-head-row">
                <th>ID</th>
                <th>Pokemon</th>
                <th>Height</th>
                <th>Weight</th>
                <th>Base Experience</th>
                <th>Sprite</th>
            </tr>
        </thead>
        <tbody class="pokemon-body">
            <% @pokemons.each do |pokemon|%>
            <tr class="pokemon-body-row">
                <td class="pokemon-body-data"><%= pokemon.id %></td>
                <td><%= pokemon.name %></td>
                <td><%= pokemon.height %></td>
                <td><%= pokemon.weight %></td>
                <td><%= pokemon.base_experience %></td>
                <% begin %>
                <td><%= link_to "View Details", pokemon_path(pokemon) %></td>
                <% end %>
            </tr>
            <% end %>
        </tbody>
    </table>
    <nav class="pagination is-centered is-info is-inverted">
        <% if @pokemons.prev_page %>
        <%= link_to "← Previous", pokemons_path(page: @pokemons.prev_page), class:"pagination-previous #{"is-disabled" unless  @pokemons.prev_page}" %>
        <% else %>
        <a class="pagination-previous" disabled>← Previous</a>
        <% end %>
        <% if @pokemons.next_page %>
        <%= link_to "Next →", pokemons_path(page: @pokemons.next_page), class:"pagination-next #{"is-disabled" unless  @pokemons.next_page}" %>
        <% else %>
        <a class="pagination-next" disabled>Next →</a>
        <% end %>

        <ul class="pagination-list">
            <% (1..@pokemons.total_pages).each do |page_num| %>
            <%= link_to page_num, pokemons_path(page: page_num), class:"pagination-link #{page_num == @pokemons.current_page ? "is-current" : ""}" %>
            <% end %>
        </ul>
    </nav>
</div>

app/views/pokemons/show.html.erb
<div class="container pokemon-card-container">
    <div class="pokemon-header has-text-centered">
        <h2 class="is-size-4">
            <%= @pokemon.name %>
        </h2>
    </div>

    <div class="pokemon-card">
        <div class="pokemon-stats has-text-centered">
            <%= image_tag @pokemon.sprite_url, alt: @pokemon.name, class:"pokemon-img-show" %>
            <p>Height: <%= @pokemon.height / 10 %> meter/s</p>
            <p>Weight: <%= @pokemon.weight / 10 %> kilogram/s</p>
            <p>Base Experience: <%= @pokemon.base_experience %></p>
        </div>

        <div class="pokemon-info has-text-centered">
            <p>
                <strong>Types:<strong>

                        <%= @pokemon.types.map(&:name).join(", ") %>
            </p>

            <% if @pokemon.abilities.any? %>
            <p>Abilities:
                <%= @pokemon.abilities.map(&:name).join(", ") %>
            </p>
            <% end %>

            <% if @pokemon.trainers.any? %>
            <p><strong>Trainers:</strong>
                <%= @pokemon.trainers.map(&:name).join(", ") %>
            </p>
            <% end %>
        </div>
    </div>
</div>

app/views/trainers/index.html.erb
<div class="trainer-header">
    <h1 class="is-size-4">
        Pokemon Trainers
    </h1>

    <h2 class="is-size-5">Below are pokemon trainers:</h2>
</div>

<div class="grid is-col-min-15 trainer-div">
    <% @trainers.each do |trainer| %>
    <div class="cell trainer-element has-text-centered">
        <%= link_to trainer.name, trainer_path(trainer), class:"trainer-link" %>
    </div>
    <% end %>
</div>

app/views/trainers/show.html.erb
<div class="container trainers-show-container">
    <div class="trainer-header">
        <h1 class="is-size-4">
            <%= @trainer.name%>
        </h1>
        <h2 class="is-size-5">Pokemons this trainer owns:</h2>
    </div>

    <div class="grid is-col-min-15 mx-4 type-div">
        <% if @trainer.pokemons.any? %>
        <% @trainer.pokemons.each do |pokemon| %>
        <div class="cell trainer-element has-text-centered">
            <%= link_to pokemon.name, pokemon_path(pokemon) %>
            <%= image_tag pokemon.sprite_url, al: pokemon.name, class: "pokemon-img" %>
        </div>
        <% end %>
        <% else %>
        <div class="has-text-centered is-size-4 my-6">
            Unfortunately, there are no pokemons with this trainer😢
        </div>
        <% end %>
    </div>
</div>

app/views/types/index.html.erb
<div class="type-header">
    <h1 class="is-size-4">
        Pokemon Types
    </h1>

    <h2 class="is-size-5">Below are the different groups a pokemon may be in:</h2>
</div>

<div class="grid is-col-min-15 type-div">
    <% @types.where.not(name: ['Stellar', 'Unknown']).each do |type| %>
    <div class="cell type-element has-text-centered">
        <%= link_to type.name, type_path(type), class:"type-link" %>
        <%= image_tag "/icons/#{type.name.downcase}.ico", alt: type.name, class:"type-icon"%>
    </div>
    <% end %>
</div>

app/views/types/show.html.erb
<div class="container types-show-container">
    <div class="type-header">
        <h1 class="is-size-4">
            <%= @type.name%> Type
        </h1>
        <h2 class="is-size-5">Pokemon with this type:</h2>
    </div>

    <div id="map" data-lat="<%= @type.latitude %>" data-lon="<%= @type.longitude %>" data-name="<%= @type.name %>" data-location="<%= @type.location_name %>" style="height: 400px; width: 100%; margin-top: 20px;">
    </div>

    <script>
        document.addEventListener("turbo:load", function() {
            var mapDiv = document.getElementById("map");

            var lat = parseFloat(mapDiv.dataset.lat) || 0;
            var lon = parseFloat(mapDiv.dataset.lon) || 0;
            var name = mapDiv.dataset.name;
            var locationName = mapDiv.dataset.location;

            var map = L.map('map').setView([lat, lon], 5);

            L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
                attribution: '&copy; OSM'
            }).addTo(map);

            if (lat && lon) {
                L.marker([lat, lon]).addTo(map)
                    .bindPopup(`<b>${name} Type</b><br>${locationName}`);
            }
        });
    </script>

    <div class="grid is-col-min-15 mx-4 type-div">
        <% if @type.pokemons.any? %>
        <% @type.pokemons.each do |pokemon| %>
        <div class="cell type-element has-text-centered">
            <%= link_to pokemon.name, pokemon_path(pokemon) %>
            <%= image_tag pokemon.sprite_url, al: pokemon.name, class: "pokemon-img" %>
        </div>
        <% end %>
        <% else %>
        <div class="has-text-centered is-size-4 my-6">
            Unfortunately, there are no pokemons with this type😢
        </div>
        <% end %>
    </div>
</div>